spring.application.name=spring-boot-app
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/atm_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secretkey=thisIsMySuperLongAndSecureKeyWithAbsolutelyNoSpecialCharactersOrUnderscoresMakeSureItIsLongEnough
spring.security.user.name=atm
spring.security.user.password=123atm
app-name=spring-boot-app
jwt.accessexpiration=3600000
jwt.refreshexpiration=86400000
api-key=atm_api_sec_8d2f7a9e4b1c3d5f6a7e8b9c0d1e2f3a

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.validate-on-migrate=true